# Generated by Django 5.2.6 on 2025-09-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_venta_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='precio_total',
            new_name='producto_precio',
        ),
        migrations.AddField(
            model_name='venta',
            name='producto_nombre',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=50),
        ),
    ]
